version: "3.9"
services:
  app:
    build: ./infra/docker/php
    volumes:
      - ./backend:/work

  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./backend:/work
      - ./infra/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  db:
    build: ./infra/docker/mysql
    volumes:
      - db-store:/var/lib/mysql
volumes:
  db-store:
